<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.certificate/xml/schema/CRM/Certificate/CompuCertificateRelationshipType.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:f5d8c30b1d166fb59c7d990226f97a30)
 */
use CRM_Certificate_ExtensionUtil as E;

/**
 * Database access object for the CompuCertificateRelationshipType entity.
 */
class CRM_Certificate_DAO_CompuCertificateRelationshipType extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'compucertificate_relationship_type';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CompuCertificateRelationshipType ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to CompuCertificate
   *
   * @var int
   */
  public $certificate_id;

  /**
   * FK to CompuCertificate
   *
   * @var int
   */
  public $relationship_type_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'compucertificate_relationship_type';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Compu Certificate Relationship Types') : E::ts('Compu Certificate Relationship Type');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'certificate_id', 'compucertificate_certificate', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'relationship_type_id', 'civicrm_relationship_type', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique CompuCertificateRelationshipType ID'),
          'required' => TRUE,
          'where' => 'compucertificate_relationship_type.id',
          'table_name' => 'compucertificate_relationship_type',
          'entity' => 'CompuCertificateRelationshipType',
          'bao' => 'CRM_Certificate_DAO_CompuCertificateRelationshipType',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'certificate_id' => [
          'name' => 'certificate_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CompuCertificate'),
          'where' => 'compucertificate_relationship_type.certificate_id',
          'table_name' => 'compucertificate_relationship_type',
          'entity' => 'CompuCertificateRelationshipType',
          'bao' => 'CRM_Certificate_DAO_CompuCertificateRelationshipType',
          'localizable' => 0,
          'FKClassName' => 'CRM_Certificate_DAO_CompuCertificate',
          'add' => NULL,
        ],
        'relationship_type_id' => [
          'name' => 'relationship_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CompuCertificate'),
          'where' => 'compucertificate_relationship_type.relationship_type_id',
          'table_name' => 'compucertificate_relationship_type',
          'entity' => 'CompuCertificateRelationshipType',
          'bao' => 'CRM_Certificate_DAO_CompuCertificateRelationshipType',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_RelationshipType',
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'compucertificate_relationship_type', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'compucertificate_relationship_type', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
